<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GreyGray.Modules.Identity.Infra</RootNamespace>
    <ModuleName>Identity</ModuleName>
    <ModuleLayer>Infra</ModuleLayer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreyGray.Modules.Identity.Core\GreyGray.Modules.Identity.Core.csproj" />
    <ProjectReference Include="..\..\..\Platform\GreyGray.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
