<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GreyGray.Modules.Inventory.Infra</RootNamespace>
    <ModuleName>Inventory</ModuleName>
    <ModuleLayer>Infra</ModuleLayer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreyGray.Modules.Inventory.Core\GreyGray.Modules.Inventory.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
