<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Daigou.Modules.Procurement.Infra</RootNamespace>
    <ModuleName>Procurement</ModuleName>
    <ModuleLayer>Infra</ModuleLayer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Daigou.Modules.Procurement.Core\Daigou.Modules.Procurement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
