<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GreyGray.M1a.IdentityCatalog.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <ModuleLayer>Test</ModuleLayer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\GreyGray.Modules.Identity.Contracts\GreyGray.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\GreyGray.Modules.Identity.Infra\GreyGray.Modules.Identity.Infra.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\GreyGray.Modules.Catalog.Contracts\GreyGray.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\GreyGray.Modules.Catalog.Infra\GreyGray.Modules.Catalog.Infra.csproj" />
    <ProjectReference Include="..\..\src\Platform\GreyGray.Platform.csproj" />
  </ItemGroup>

</Project>
