/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 團隊成員登入 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Staff"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 目前登入的團隊成員 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Staff"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分類清單 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        /** 新增分類 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description 已建立 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description `catalog.invalid-category` · `catalog.invalid-parent-category` · `catalog.category-depth-exceeded`（ADR-041） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改分類 */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    categoryId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description `catalog.invalid-category` · `catalog.invalid-parent-category` · `catalog.category-depth-exceeded`（ADR-041） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品列表 */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    categoryId?: components["schemas"]["Id"];
                    includeArchived?: boolean;
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AdminProduct"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 建立商品
         * @description **`weightGram` 與 `size` 在 M1a 就要填。** M1a 運費一口價用不到，
         *     但等 M3 啟用材積重計費時資料已經在那裡了——回頭補幾百筆商品尺寸是純粹的浪費。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminProductInput"];
                };
            };
            responses: {
                /** @description 已建立 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminProduct"];
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** 商品詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminProduct"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改商品 */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    productId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminProductInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminProduct"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/v1/products/{productId}/skus": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 建立 SKU
         * @description ADR-032：凍結契約的第一次純新增。商品可先建為空 SKU 集，首個與之後的 SKU 都從這裡建；
         *     **`weightGram` 與 `size` 必填**（M1a 起就是，不可捏造預設值）；`listPrice` 現貨才填，預購 SKU 售價在開團定。
         *     SKU 的內部 ID 一經產生不可變（通路擴充接縫 #2）。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    productId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSkuInput"];
                };
            };
            responses: {
                /** @description 已建立 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminSku"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skus/{skuId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skuId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改 SKU
         * @description **SKU 的內部 ID 一經產生不可變**（通路擴充接縫 #2）。
         *     不要拿商品編號、條碼或名稱當識別——外部平台的 ID 對不回來時，同步只能靠人工比對。
         */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    skuId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSkuInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminSku"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 開團列表 */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["CampaignStatus"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AdminCampaign"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 建立開團（草稿）
         * @description **一趟旅程對應一個團（1:1）**，所以旅程成本直接掛在團上，不需要任何攤分規則。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminCampaignInput"];
                };
            };
            responses: {
                /** @description 已建立，狀態 `Draft` */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaign"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** 開團詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaignDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改開團 */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminCampaignInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaign"];
                    };
                };
                /** @description `campaign.cannot-edit-after-publish` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 發布開團（Draft → Open） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaign"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提前截團（Open → Closed）
         * @description 正常情況由 Saga Timer 在 `closesAt` 自動截團，這個端點是**人工提前**用的。
         *     截團後 Procurement 會收到 `CampaignClosed` 並產出採購清單。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaign"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消開團
         * @description 該團全部訂單取消並退款。
         *     **已登錄的旅程成本仍然留在帳上**——機票已經買了就是真實損失，
         *     不能因為團沒成就假裝沒發生。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaign"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 結團
         * @description 該團所有訂單皆已出貨後才能結團，結完 Reporting 會算出每團真實毛利。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaign"];
                    };
                };
                /** @description `campaign.orders-not-all-shipped` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** 開團商品清單 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaignOffer"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * 加入開團商品
         * @description `sellingPrice` **一經發布即定死**。`targetPurchasePrice` 只是給自己看的參考，
         *     現場買貴買便宜都不影響已成立的訂單。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        skuId: components["schemas"]["Id"];
                        sellingPrice: components["schemas"]["Money"];
                        targetPurchasePrice?: components["schemas"]["Money"] | null;
                    };
                };
            };
            responses: {
                /** @description 已加入 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCampaignOffer"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/offers/{offerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 移除開團商品
         * @description **已經有人下單的商品不可移除**，只能設成 `isActive = false` 停止收單——
         *     移除了那些訂單的 line 就會指向不存在的 offer。後端會擋，回 422。
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                    offerId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已移除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description `campaign.offer-has-orders` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/trip-costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登錄旅程成本（M1b）
         * @description **M1b。** Ledger 訂閱後開分錄 DR 旅程成本 / CR 現金。
         *     團被取消時這筆仍然要入帳。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        kind: components["schemas"]["TripCostKind"];
                        amount: components["schemas"]["Money"];
                        memo?: string | null;
                    };
                };
            };
            responses: {
                /** @description 已登錄 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 訂單列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 單號或客戶暱稱 */
                    q?: string;
                    status?: components["schemas"]["OrderStatus"];
                    campaignId?: components["schemas"]["Id"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AdminOrderListItem"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 訂單詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消整張訂單並退款 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orderId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                        /** @description 客人自己選的退款去向，不是營運代選（ADR-023）。 */
                        refundTo: components["schemas"]["RefundDestination"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/lines/{lineId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消單一品項並退款
         * @description 現場缺貨時用。**其餘 line 續行，訂單不整張作廢**——
         *     這是這門生意最常見的補償路徑，不是邊緣案例。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orderId: components["schemas"]["Id"];
                    lineId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                        /** @description 客人自己選的退款去向，不是營運代選（ADR-023）。 */
                        refundTo: components["schemas"]["RefundDestination"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/lines/{lineId}/refund-shortfall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 退還部分買到的短缺數量
         * @description 部分買到（ADR-026）時用：買到的數量照常出貨，**短缺的數量退款**。
         *     標記買到的當下不問退款去向，短缺數量先掛在 line 上；客人選好之後才呼叫這裡，
         *     這一刻才真的退款、把 `quantity` 減成實際出貨數量並調降訂單總額。
         *     一次性決策，退過就不能反悔改去向。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orderId: components["schemas"]["Id"];
                    lineId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                        /** @description 客人自己選的退款去向，不是營運代選（ADR-023）。 */
                        refundTo: components["schemas"]["RefundDestination"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}/purchase-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 該團的採購清單（M1b）
         * @description **M1b。** 截團後由 `CampaignClosed` 產生。
         *     **系統不下單給任何人**——它記錄的是你人站在店裡做了什麼決定。
         *
         *     這個畫面要能在手機上單手操作，因為使用情境就是站在藥妝店裡。
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["PurchaseItemStatus"];
                };
                header?: never;
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/purchase-items/{purchaseItemId}/purchased": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 標記買到（M1b） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    purchaseItemId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        quantityPurchased: number;
                        /** @description 當地幣別的實付金額。資訊欄位，**不產生分錄**。 */
                        actualPaidOriginal: components["schemas"]["Money"];
                        /**
                         * @description 記帳幣（TWD）的實付金額，**這個才入帳**。
                         *     現場刷卡即時結清，成本就是刷卡帳單上的台幣金額——本專案不做匯兌損益。
                         */
                        actualPaidBooking: components["schemas"]["Money"];
                    };
                };
            };
            responses: {
                /** @description 已記錄 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/purchase-items/{purchaseItemId}/unavailable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 標記缺貨（M1b）
         * @description 該 OrderLine 取消並退款，其餘 line 續行。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    purchaseItemId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 已記錄 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/purchase-items/{purchaseItemId}/price-changed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 回報現場漲價（M1b）
         * @description **發完就放行，不等回覆。** 系統發 LINE 問客人並記錄軌跡，
         *     逾時視為照買，差額由賣方吸收（團價已定死）。
         *
         *     這個端點回應後你就可以繼續買下一項——**不會有任何東西卡住你**。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    purchaseItemId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        newPrice: components["schemas"]["Money"];
                    };
                };
            };
            responses: {
                /** @description 已通知客人並開啟詢價軌跡 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inquiryId: components["schemas"]["Id"];
                            /**
                             * Format: date-time
                             * @description 到這個時間還沒回覆就自動視為照買。
                             */
                            timeoutAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 出貨單列表（M1b） */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ShipmentStatus"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AdminShipment"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 建立出貨單（M1b）
         * @description **Order 與 Shipment 是 N:M。** 一張訂單可拆多個包裹；
         *     一個包裹也可含同一客人的多張訂單（合併出貨省運費）。這是日常，不是邊緣案例。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        orderIds: components["schemas"]["Id"][];
                        method: components["schemas"]["DeliveryMethod"];
                    };
                };
            };
            responses: {
                /** @description 已建立 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminShipment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments/{shipmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 出貨單詳情（第七波，BE-19）
         * @description **第七波新增。** 契約原本只有列表／建立／`dispatch`／`deliver` 四條，
         *     沒有單筆查詢——前端只能撈 `limit:100` 的列表再自己過濾，
         *     出貨單超過 100 張之後點詳情會白頁而且不報錯。這條補上單筆查詢。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shipmentId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminShipment"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments/{shipmentId}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 交運（M1b）
         * @description `carrierCost` 是**你付給物流商的成本**，不是你向客人收的運費——
         *     後者在訂單的 `shippingFee` 裡。兩個是獨立的數字，月結時運費是賺是賠自己會浮出來。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    shipmentId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        trackingNumber: string;
                        carrierCost: components["schemas"]["Money"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminShipment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments/{shipmentId}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 標記已送達（M1b）
         * @description **M1b。** 正常情況由物流商的回報自動觸發，這個端點是人工補登用的
         *     （例如面交自取，物流商不會有任何回報）。
         *
         *     送達不等於完成——訂單要等鑑賞期屆滿才轉 `Completed`，
         *     那條是 Saga Timer 的事，不在這裡。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    shipmentId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminShipment"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 批號列表（M2） */
        get: {
            parameters: {
                query?: {
                    skuId?: components["schemas"]["Id"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Lot"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 批發進貨（M2）
         * @description **批號是成本的載體**——批號別實際成本，出貨時從指定批號結轉銷貨成本。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        skuId: components["schemas"]["Id"];
                        quantity: number;
                        unitCost: components["schemas"]["Money"];
                        batchCode?: string | null;
                    };
                };
            };
            responses: {
                /** @description 已建立 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lot"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分錄查詢
         * @description 用 `sourceModule` ＋ `sourceRef` 反查——**每個數字都要能追回是哪張訂單造成的**。
         */
        get: {
            parameters: {
                query?: {
                    sourceModule?: string;
                    sourceRef?: string;
                    from?: string;
                    to?: string;
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["JournalEntry"][];
                            nextCursor: string | null;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/campaign-margin/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 每團真實毛利
         * @description ＝ 銷貨收入 − 銷貨成本 ＋ 運費收入 − 運費成本 − 旅程成本。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignMargin"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/liability-vs-cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 負債與現金對照
         * @description `isBreached = true` 代表**你正在用還沒交貨的錢過日子**。
         *     這是代購生意最典型的崩壞前兆——後台首頁要把它放在看得到的地方。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiabilityVsCash"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 客服訊息列表
         * @description 前台右下角小幫手收到的留言（ADR-040）。游標式分頁，**不回總筆數**。
         *     預設由新到舊。
         */
        get: operations["listSupportTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/support/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 單一客服訊息 */
        get: operations["getSupportTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/support/tickets/{ticketId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 標記已處理
         * @description ⚠ `Operator` 與 `Accountant` 是**平行角色**，不是等級高低——
         *     權限判斷不要用 enum 大小比較。
         */
        post: operations["resolveSupportTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description UUIDv7，32 字元十六進位，無連字號。 */
        Id: string;
        /** @enum {string} */
        Currency: "TWD" | "JPY" | "USD" | "KRW" | "EUR" | "HKD" | "CNY" | "THB" | "GBP" | "SGD";
        /** @description `amountMinor` 是最小單位。TWD：`NT$180` = `18000`。 */
        Money: {
            /** Format: int64 */
            amountMinor: number;
            currency: components["schemas"]["Currency"];
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
            code: string;
            traceId?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * @description 權限判斷寫在模組內的 Policy，**不是 controller 裡的 `if role == admin`**。
         *     排序（權限由高到低）：Owner > Accountant ≈ Operator > ReadOnly。
         * @enum {string}
         */
        StaffRole: "Owner" | "Operator" | "Accountant" | "ReadOnly";
        Staff: {
            id: components["schemas"]["Id"];
            displayName: string;
            email?: string;
            role: components["schemas"]["StaffRole"];
        };
        /** @enum {string} */
        FulfillmentMode: "Stock" | "Preorder";
        /** @enum {string} */
        ShippingPolicy: "ShipSeparately" | "HoldUntilComplete";
        /** @enum {string} */
        DeliveryMethod: "ConvenienceStore" | "HomeDelivery" | "SelfPickup";
        /** @enum {string} */
        CampaignStatus: "Draft" | "Open" | "Closed" | "TripInProgress" | "Returned" | "Settled" | "Cancelled";
        /** @enum {string} */
        OrderStatus: "AwaitingPayment" | "PaidAwaitingClose" | "ClosedAwaitingDeparture" | "Purchasing" | "GoodsReceived" | "ReadyToShip" | "Shipped" | "Completed" | "Cancelled";
        /** @enum {string} */
        OrderLineStatus: "Pending" | "Reserved" | "Purchased" | "Unavailable" | "Shipped" | "Completed" | "Cancelled";
        /** @enum {string} */
        PaymentStatus: "Pending" | "Captured" | "Failed" | "Refunded" | "PartiallyRefunded";
        /** @enum {string} */
        PaymentProvider: "ECPay" | "NewebPay" | "LinePay" | "ExternalSettled";
        /** @enum {string} */
        ShipmentStatus: "Draft" | "Packed" | "Dispatched" | "InTransit" | "ArrivedAtStore" | "Delivered" | "Returned" | "Lost";
        /**
         * @description `StoredValue` 完全不動金流、零手續費。優先建議客人選這個。
         *     M1b 期間 `StoredValue` 不開放，選了會回可預期的業務失敗（Result，不是例外）；M3 開啟。
         * @enum {string}
         */
        RefundDestination: "OriginalPaymentMethod" | "StoredValue";
        /**
         * @description `PriceChangedPendingConfirmation` **不是阻塞狀態**——通知發出去就繼續。
         * @enum {string}
         */
        PurchaseItemStatus: "Pending" | "Purchased" | "PriceChangedPendingConfirmation" | "Unavailable";
        /**
         * @description M1a 全部記在同一個「旅程成本」科目下，細分排 M6+。
         * @enum {string}
         */
        TripCostKind: "Airfare" | "Accommodation" | "ExcessBaggage" | "CustomsDuty" | "LocalTransport" | "Other";
        /** @enum {string} */
        LotSource: "LocalWholesale" | "OverseasPurchase" | "CustomerReturn";
        /** @enum {string} */
        Direction: "Debit" | "Credit";
        Dimensions: {
            lengthCm: number;
            widthCm: number;
            heightCm: number;
        };
        CategoryInput: {
            name: string;
            imageUrl?: string | null;
            /** @default 0 */
            sortOrder: number;
            /** @description 上層分類。省略或 null＝根分類（PATCH 是整筆取代，與 imageUrl、sortOrder 相同）。分類固定兩層：只能指向根分類，已有子分類者不能變成子分類，不能指向自己（ADR-041）。違反時 422 catalog.invalid-parent-category（不存在、跨租戶、指向自己）或 catalog.category-depth-exceeded（上層不是根分類、自己已有子分類）。 */
            parentId?: components["schemas"]["Id"] | null;
        };
        Category: {
            id: components["schemas"]["Id"];
        } & components["schemas"]["CategoryInput"];
        AdminSkuInput: {
            name: string;
            variantName?: string | null;
            weightGram: number;
            size: components["schemas"]["Dimensions"];
            unitOfMeasure?: string | null;
            unitCount?: number | null;
            /** @description 現貨標價。預購 SKU 不用填（售價在開團定）。 */
            listPrice?: components["schemas"]["Money"] | null;
            /** @default true */
            isActive: boolean;
        };
        AdminSku: {
            id: components["schemas"]["Id"];
            /** @description 可用 ＝ 總量 − 保留 − 通路配額（第三項 M5 前恆為 0）。 */
            available: number;
        } & components["schemas"]["AdminSkuInput"];
        AdminProductInput: {
            name: string;
            description?: string | null;
            shortDescription?: string | null;
            categoryId?: components["schemas"]["Id"] | null;
            mode: components["schemas"]["FulfillmentMode"];
            images?: string[];
            /** @default true */
            isActive: boolean;
        };
        AdminProduct: {
            id: components["schemas"]["Id"];
            skus: components["schemas"]["AdminSku"][];
        } & components["schemas"]["AdminProductInput"];
        AdminCampaignInput: {
            title: string;
            destination: string;
            /** Format: date */
            departAt: string;
            /** Format: date */
            returnAt: string;
            /**
             * Format: date-time
             * @description 到這個時間 Saga Timer 會自動截團。
             */
            closesAt: string;
            /**
             * @description 現場漲價詢問的逾時分鐘數（ADR-027，每團可設）。
             *     **不填的話用 120（2 小時）當預設值**——這是技術預設值，不是業務規則；
             *     日本藥妝店與精品店現場的節奏不一樣，才開放每團指定。
             */
            priceInquiryTimeoutMinutes?: number | null;
            description?: string | null;
            coverImageUrl?: string | null;
        };
        AdminCampaign: {
            id: components["schemas"]["Id"];
            status: components["schemas"]["CampaignStatus"];
            orderCount: number;
            /** @description 回國前是 0。 */
            tripCostTotal?: components["schemas"]["Money"] | null;
        } & components["schemas"]["AdminCampaignInput"];
        AdminCampaignDetail: components["schemas"]["AdminCampaign"] & {
            offers: components["schemas"]["AdminCampaignOffer"][];
        };
        AdminCampaignOffer: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            sellingPrice: components["schemas"]["Money"];
            targetPurchasePrice?: components["schemas"]["Money"] | null;
            isActive: boolean;
            /** @description 目前已被下單的總數量。採購清單就是照這個產生的。 */
            orderedQuantity: number;
        };
        AdminOrderListItem: {
            id: components["schemas"]["Id"];
            orderNumber: string;
            customerId?: components["schemas"]["Id"];
            customerDisplayName: string;
            status: components["schemas"]["OrderStatus"];
            grandTotal: components["schemas"]["Money"];
            /** Format: date-time */
            placedAt: string;
            campaignId?: components["schemas"]["Id"] | null;
        };
        AdminOrderLine: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            mode: components["schemas"]["FulfillmentMode"];
            status: components["schemas"]["OrderLineStatus"];
            quantity: number;
            unitPrice: components["schemas"]["Money"];
            lineTotal: components["schemas"]["Money"];
            /**
             * @description 部分買到時短缺、等待退款決定的數量（ADR-026）；0 表示沒有短缺。
             *     `quantity` 是實際要出貨的數量，短缺退款完成後才會扣掉這個數量；
             *     本欄位退款後保留原值供追溯，所以「還在等退款決定」要看
             *     `quantityShortfall > 0 且 refundedAmount 為 null`。
             */
            quantityShortfall?: number;
            /** @description 該品項已完成或已要求的退款金額；未退款時為 null。 */
            refundedAmount?: components["schemas"]["Money"] | null;
            campaignId?: components["schemas"]["Id"] | null;
            /** @description 出貨時實際結轉成本的批號。 */
            consumedLotId?: components["schemas"]["Id"] | null;
        };
        AdminOrder: components["schemas"]["AdminOrderListItem"] & {
            goodsTotal: components["schemas"]["Money"];
            shippingFee: components["schemas"]["Money"];
            deliveryMethod: components["schemas"]["DeliveryMethod"];
            shippingPolicy: components["schemas"]["ShippingPolicy"];
            /** @description 超商取貨的門市代號（ADR-038）；其他配送方式為 null。 */
            convenienceStoreCode?: string | null;
            /** @description 超商取貨的門市名稱（下單當時凍結）；ADR-038 之前的舊訂單只有代號，這裡是 null。 */
            convenienceStoreName?: string | null;
            /** @description 超商取貨的門市地址（下單當時凍結）；舊訂單為 null。 */
            convenienceStoreAddress?: string | null;
            lines: components["schemas"]["AdminOrderLine"][];
            payments?: components["schemas"]["PaymentSummary"][];
            quoteExplain?: string[];
            /**
             * @description 收件人真實姓名，**明文**（ADR-039）。下單當時凍結，不會跟著地址簿變動。
             *     超商取貨是客人填的、宅配是從地址簿抄的；ADR-039 之前的舊訂單為 null。
             *     **出貨要用這個**——姓名與證件不符時超商會拒絕交貨。
             */
            recipientName?: string | null;
            /** @description 收件人手機，明文（ADR-039）。規則同 `recipientName`。 */
            recipientPhone?: string | null;
            /**
             * @description 宅配收件地址的**完整單行字串**，下單當時凍結（ADR-039）。
             *     超商取貨的訂單為 null（門市看 `convenienceStore*` 三個欄位）；
             *     ADR-039 之前的舊訂單也是 null。
             *
             *     **出貨要用這個**——後台沒有這個欄位以前，宅配訂單在後台看不到地址，
             *     等於寄不出去。刻意存成單行字串而不是拆成結構化欄位：
             *     後台出貨只需要「印出來貼在包裹上」的地址，拆開反而要在前端再拼一次。
             */
            recipientAddress?: string | null;
            /**
             * @description **已由 `recipientName` 與 `recipientPhone` 取代，恆為 `null`；保留欄位只為相容既有用戶端。**
             *
             *     舊描述寫的是「要看明文必須另外呼叫並填寫存取理由，每一次讀取都會寫進 audit」——
             *     **那個端點從來沒有實作過**，而且 2026-09-19 使用者拍板改為
             *     **後台全員直接看得到明文、不遮罩、不加解鎖閘門**（ADR-039 記了這個取捨與它的失效條件）。
             */
            customerContactMasked?: string | null;
        };
        PaymentSummary: {
            id: components["schemas"]["Id"];
            provider: components["schemas"]["PaymentProvider"];
            status: components["schemas"]["PaymentStatus"];
            amount: components["schemas"]["Money"];
            fee?: components["schemas"]["Money"] | null;
            providerTransactionId?: string | null;
            /** Format: date-time */
            capturedAt?: string | null;
            /**
             * Format: date-time
             * @description 撥款到帳時間。**客人付款當下錢在金流商手上，不在你的帳戶**——
             *     在途轉現金要等這個時間點。
             */
            settledAt?: string | null;
        };
        PurchaseItem: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            imageUrl?: string | null;
            orderLineId?: components["schemas"]["Id"];
            orderNumber?: string;
            quantityRequested: number;
            quantityPurchased: number;
            targetPrice?: components["schemas"]["Money"] | null;
            status: components["schemas"]["PurchaseItemStatus"];
            /** Format: date-time */
            decidedAt?: string | null;
            /** @description 有回報過漲價才有值。 */
            inquiry?: components["schemas"]["Inquiry"] | null;
        };
        /** @description 現場詢價的軌跡。**糾紛時這份軌跡就是證據。** */
        Inquiry: {
            id: components["schemas"]["Id"];
            originalPrice: components["schemas"]["Money"];
            newPrice: components["schemas"]["Money"];
            /** Format: date-time */
            askedAt: string;
            /** Format: date-time */
            timeoutAt: string;
            /** Format: date-time */
            repliedAt?: string | null;
            /** @enum {string|null} */
            outcome?: "ConfirmedByCustomer" | "DeclinedByCustomer" | "AutoApprovedOnTimeout" | null;
            replyText?: string | null;
        };
        AdminShipment: {
            id: components["schemas"]["Id"];
            method: components["schemas"]["DeliveryMethod"];
            status: components["schemas"]["ShipmentStatus"];
            trackingNumber?: string | null;
            orderIds: components["schemas"]["Id"][];
            /** @description 付給物流商的成本，與向客人收的運費是兩個獨立的數字。 */
            carrierCost?: components["schemas"]["Money"] | null;
            /** Format: date-time */
            dispatchedAt?: string | null;
            /** Format: date-time */
            deliveredAt?: string | null;
        };
        Lot: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            skuName?: string;
            source: components["schemas"]["LotSource"];
            unitCost: components["schemas"]["Money"];
            quantityOnHand: number;
            quantityReserved: number;
            quantityAvailable: number;
            batchCode?: string | null;
            fromCampaignId?: components["schemas"]["Id"] | null;
            /** Format: date-time */
            receivedAt: string;
        };
        JournalLine: {
            /** @example 2110 */
            accountCode: string;
            /** @example 預收貨款 */
            accountName: string;
            direction: components["schemas"]["Direction"];
            amount: components["schemas"]["Money"];
        };
        /**
         * @description **分錄一經 posted 即不可修改**——更正只能開反向分錄（紅字沖銷）。
         *     所以這裡沒有 PATCH 也沒有 DELETE，那不是遺漏。
         */
        JournalEntry: {
            id: components["schemas"]["Id"];
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            postedAt: string;
            sourceModule: string;
            sourceRef: string;
            memo?: string;
            lines: components["schemas"]["JournalLine"][];
        };
        CampaignMargin: {
            campaignId: components["schemas"]["Id"];
            salesRevenue: components["schemas"]["Money"];
            costOfGoodsSold: components["schemas"]["Money"];
            shippingRevenue: components["schemas"]["Money"];
            shippingCost: components["schemas"]["Money"];
            tripCost: components["schemas"]["Money"];
            /** @description 後端算好的。**前端不要自己加減。** */
            grossMargin: components["schemas"]["Money"];
        };
        LiabilityVsCash: {
            /** @description 預收貨款 ＋ 預收運費 ＋ 客戶儲值金。 */
            customerLiabilityTotal: components["schemas"]["Money"];
            cashTotal: components["schemas"]["Money"];
            /** @description true 代表**你正在用還沒交貨的錢過日子**。首頁要顯眼。 */
            isBreached: boolean;
            /** Format: date-time */
            asOf: string;
        };
        /** @enum {string} */
        SupportTicketStatus: "open" | "resolved";
        SupportTicket: {
            id: components["schemas"]["Id"];
            status: components["schemas"]["SupportTicketStatus"];
            message: string;
            contactEmail?: string | null;
            contactPhone?: string | null;
            /**
             * @description 客人在小幫手裡走過的選單路徑。**客服要先看這個**——
             *     只有一句「不能用」而不知道他卡在哪一題，回覆只能猜。
             */
            menuPath?: string[];
            orderId?: components["schemas"]["Id"] | null;
            /** @description 匿名留言為 null。 */
            customerId?: components["schemas"]["Id"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
            resolvedBy?: string | null;
            staffNote?: string | null;
        };
        SupportTicketPage: {
            items: components["schemas"]["SupportTicket"][];
            /** @description null 代表沒有下一頁。**不回總筆數**（游標式分頁的慣例）。 */
            nextCursor?: string | null;
        };
    };
    responses: {
        /** @description 未登入或 session 過期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description 已登入但角色不足。**Cloudflare Access 管的是誰進得來，不是進來能做什麼**——
         *     這一層檢查不可以省。
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 欄位驗證失敗或業務規則不允許 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 觸發速率限制 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSupportTickets: {
        parameters: {
            query?: {
                /** @description 只看某個狀態；省略為全部。**未結案的優先看**。 */
                status?: components["schemas"]["SupportTicketStatus"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTicketPage"];
                };
            };
        };
    };
    getSupportTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTicket"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resolveSupportTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    staffNote?: string | null;
                };
            };
        };
        responses: {
            /** @description 已標記 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTicket"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `support.already-resolved`（別人剛處理過） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
