/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 註冊
         * @description **欄位已定案（ADR-019）。** 歷史會員與訂單不從租用平台遷移，
         *     客人在新站重新註冊；Google 帳號串接排在 M1a 之後。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 建立成功，同時登入 */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["SessionCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登入
         * @description M1a 只有「手機號碼 ＋ 密碼」。LINE Login 綁定排 M1b。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 0912345678 */
                        phoneNumber: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登入成功 */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["SessionCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /**
                 * @description 帳號或密碼錯誤。`code: identity.invalid-credentials`。
                 *     **刻意不區分「帳號不存在」與「密碼錯誤」**——區分了等於送對方一份帳號列舉工具。
                 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出，session cookie 已清除 */
                204: {
                    headers: {
                        /** @description gg_session=; Max-Age=0 */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 目前登入的客戶 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改非敏感欄位
         * @description 手機號碼與身分證字號不在這裡改——那是需要二次驗證的流程，排 M1b。
         */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName?: string;
                        /** Format: email */
                        email?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/v1/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的收件地址 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShippingAddress"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 新增收件地址 */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShippingAddressInput"];
                };
            };
            responses: {
                /** @description 已建立 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShippingAddress"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** 修改收件地址 */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    addressId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShippingAddressInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShippingAddress"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** 刪除收件地址 */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    addressId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已刪除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/stored-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 儲值金餘額
         * @description 來自 Ledger 的 `IStoredValueQuery`。
         *     退款走儲值金完全不動金流、零手續費，所以這個數字在退款流程裡會被看到。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            balance: components["schemas"]["Money"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的最愛
         * @description 最新收藏的在前（ADR-036）。**只列出目前看得到的商品**——判定與 `GET /v1/products/{productId}` 相同
         *     （商品上架，而且至少有一個上架中的規格），在分頁之前過濾。
         *     收藏之後不再符合的商品不會刪掉收藏紀錄，只是不出現在這裡；恢復之後就會回來。
         *     清單裡的商品可能還沒定價（`priceFrom` 為 `null`）。每一筆的 `isFavorited` 恆為 `true`。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 上一頁回傳的 `nextCursor`。第一頁不帶。 */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ProductListItem"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description `catalog.invalid-cursor`（cursor 無效，或 limit 不在 1 到 100 之間） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 加入最愛
         * @description **冪等**：已經在最愛裡再加一次也回 `204`。
         *     可收藏的判定與 `GET /v1/products/{productId}` 相同——那支回 `404` 的（不存在或已下架），這裡也回 `404`。
         */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    productId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已在最愛裡 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * 移出最愛
         * @description **冪等**：本來就不在最愛裡也回 `204`，也不因商品已下架而失敗。
         *     只有 `productId` 格式不合法時回 `404`（與其他路由參數一致）。
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    productId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已不在最愛裡 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分類清單
         * @description 前台「橫捲圓形分類標」的資料來源。回傳的是已發布且底下有上架商品的分類。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 商品列表
         * @description 商品卡牆。**不含價格明細**——價格屬於開團定價或現貨標價，見 `priceFrom`。
         */
        get: {
            parameters: {
                query?: {
                    categoryId?: components["schemas"]["Id"];
                    /** @description 關鍵字，比對商品名稱與變體名稱 */
                    q?: string;
                    /** @description 只看現貨或只看預購 */
                    mode?: components["schemas"]["FulfillmentMode"];
                    /** @description 上一頁回傳的 `nextCursor`。第一頁不帶。 */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ProductListItem"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 商品詳情
         * @description 含所有 SKU、可用量、以及（若屬於進行中的團）該團的售價。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 開團列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 不給的話只回 `Open` */
                    status?: components["schemas"]["CampaignStatus"];
                    /** @description 上一頁回傳的 `nextCursor`。第一頁不帶。 */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["CampaignListItem"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 開團詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得購物車
         * @description 未登入也可以有購物車（以 cookie 綁匿名 cart）。結帳時才要求登入。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 加入購物車 */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        skuId: components["schemas"]["Id"];
                        mode: components["schemas"]["FulfillmentMode"];
                        /** @description `mode = Preorder` 時必填。 */
                        campaignOfferId?: components["schemas"]["Id"] | null;
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description 已加入，回傳整個購物車 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                /**
                 * @description `catalog.sku-not-found` · `catalog.sku-archived` ·
                 *     `campaign.not-accepting-orders` · `inventory.insufficient-stock`
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除品項 */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    lineId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 改數量 */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    lineId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/v1/cart/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 詢價
         * @description **純函式語意：不寫入任何東西**，同樣輸入永遠同樣輸出（給定同一個 ACTIVE 規則集）。
         *     客人切換配送方式時就呼叫，用來顯示「購物袋含運總額」。
         *
         *     M1a 費率是一口價（超商 60／宅配 120／自取 0），
         *     但 `explain` 仍然完整回傳——客服要能直接回答「為什麼收這麼多」。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        deliveryMethod: components["schemas"]["DeliveryMethod"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteResult"];
                    };
                };
                /** @description `checkout.cart-empty` · `pricing.no-active-rule-set` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 結帳
         * @description 建立訂單。**這裡會再詢價一次並把報價凍結成不可變快照**——
         *     之後改運費規則不影響已成立的訂單。
         *
         *     混合訂單（同時有現貨與預購 line）必須指定 `shippingPolicy`：
         *     現貨先出會付兩次運費，等回國一起出省一次。**這是客人下單時就要選的，不是出貨時才問。**
         *     **單一模式的購物車不用選**——後端依 line 組成推導（ADR-030）。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        deliveryMethod: components["schemas"]["DeliveryMethod"];
                        /**
                         * @description `Cart.hasMixedModes = true` 時必填（缺了回 `422` `checkout.shipping-policy-required`）；
                         *     單一模式可省略或 `null`，後端依 line 組成推導：純現貨 → `ShipSeparately`、
                         *     純預購 → `HoldUntilComplete`。單一模式時客人送的值會被忽略，不會因此報錯。
                         */
                        shippingPolicy?: components["schemas"]["ShippingPolicy"] | null;
                        /** @description `deliveryMethod = HomeDelivery` 時必填。 */
                        shippingAddressId?: components["schemas"]["Id"] | null;
                        /**
                         * @description `deliveryMethod = ConvenienceStore` 時**建議**帶這個（ADR-038）：`/v1/logistics/cvs-selections/{selectionId}` 的選店票。
                         *     後端從選店票取出門市代號、名稱、地址凍結進訂單。票過期、不存在或屬於別台購物車回 `422 checkout.store-selection-expired`。
                         *     同時帶了 `convenienceStoreCode` 時以這個為準、忽略代號。
                         */
                        convenienceStoreSelectionId?: string | null;
                        /**
                         * @description **相容舊用戶端**：沒帶 `convenienceStoreSelectionId` 時才看這個。只有代號、沒有名稱與地址。
                         *     `deliveryMethod = ConvenienceStore` 時兩者至少要有一個，都沒有回 `422 checkout.store-code-required`。
                         */
                        convenienceStoreCode?: string | null;
                        buyerNote?: string | null;
                    };
                };
            };
            responses: {
                /** @description 訂單已建立，狀態 `AwaitingPayment` */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
                /**
                 * @description `checkout.cart-empty` · `checkout.address-required` ·
                 *     `checkout.store-code-required` · `checkout.store-selection-expired` ·
                 *     `checkout.shipping-policy-required` ·
                 *     `campaign.not-accepting-orders` · `inventory.insufficient-stock` ·
                 *     `payment.provider-does-not-support-delivery-method`
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的訂單 */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["OrderStatus"];
                    /** @description 上一頁回傳的 `nextCursor`。第一頁不帶。 */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["OrderListItem"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 訂單詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 不存在，**或存在但不屬於這個客戶**。刻意不區分——區分了會洩漏訂單編號的存在性。 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自助取消訂單
         * @description **只有 `AwaitingPayment` 的訂單可以自助取消。** 已付款的取消要走客服，
         *     因為牽涉退款去向（原路 vs 儲值金）與已發生的成本。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orderId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string | null;
                    };
                };
            };
            responses: {
                /** @description 已取消 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description `ordering.cannot-self-cancel-after-payment` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取得付款導轉參數
         * @description 回傳一組要 POST 到綠界的表單參數。**前端不自己組簽章**——
         *     `checkMacValue` 由後端算好，前端只負責把 `fields` 原封不動送出去。
         *
         *     M1a 只有綠界（ADR-011）。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orderId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentInitiation"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description `ordering.order-already-paid` · `ordering.order-cancelled` */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logistics/cvs-map-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 開啟 7-ELEVEN 電子地圖（產生一次性選店票）
         * @description 綁定目前的購物車（`gg_cart` cookie），**不需要登入**——選門市在送出訂單之前。
         *     回傳綠界電子地圖的導轉參數：前端建一個 hidden form，把 `fields` 原封不動用 `method` 送到 `action`，
         *     **頂層導向**（不可放 iframe、iOS 不可開新視窗）。選店票 15 分鐘內有效、只能用一次（ADR-038）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 綠界地圖載入電腦版還是手機版；不帶由綠界自己判斷。 */
                        device?: ("Desktop" | "Mobile") | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CvsMapSession"];
                    };
                };
                /** @description `logistics.not-configured`：這台伺服器沒有物流設定，客人要改選其他配送方式 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logistics/cvs-map/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 綠界電子地圖回傳（不是給前端呼叫的）
         * @description 綠界經**客人的瀏覽器**以表單 POST 回來。這份回傳**沒有檢查碼**，所以後端驗：選店票（`ExtraData`）存在、未過期、未用過，
         *     `MerchantID` 與 `LogisticsSubType` 與設定相符，門市欄位的格式與長度。
         *     一律 **303** 導回 `{Storefront:PublicOrigin}/checkout`：成功帶 `cvsSelection=<選店票>`，失敗帶 `cvsSelectionError=<錯誤碼>`。
         *     不回 JSON、不給客人看 500。門市名稱與地址**不放在導回網址裡**。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        MerchantID?: string;
                        MerchantTradeNo?: string;
                        LogisticsSubType?: string;
                        CVSStoreID?: string;
                        CVSStoreName?: string;
                        CVSAddress?: string;
                        CVSTelephone?: string;
                        CVSOutSide?: string;
                        ExtraData?: string;
                    };
                };
            };
            responses: {
                /** @description 導回結帳頁（成功或失敗都是 303） */
                303: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logistics/cvs-selections/{selectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selectionId: string;
            };
            cookie?: never;
        };
        /**
         * 讀取選好的門市
         * @description 只有**同一台購物車**讀得到；不存在、過期、或屬於別台購物車一律回 `404`（不區分，免得被拿來猜票）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    selectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CvsStoreSelection"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/ecpay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 綠界回呼
         * @description **不是給前端的端點。** 列在這裡是因為它屬於 Storefront 行程的路由表。
         *
         *     三件事缺一不可：驗簽（`CheckMacValue`）、時戳容忍窗、`MerchantTradeNo` 去重。
         *     綠界會重送，所以這個端點必須冪等——去重走 `platform.idempotency_key`。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description 綠界要求回應純文字 `1|OK`。**不是 JSON。** */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 訂單的出貨紀錄
         * @description **M1b。** 一張訂單可拆多個包裹；一個包裹也可含同一客人的多張訂單（合併出貨省運費）。
         *     所以這裡回的是陣列，不是單一物件——這是日常，不是邊緣案例。
         *
         *     M1a 期間這個端點回空陣列，前端要能正常顯示「尚未出貨」。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shipment"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inquiries/{inquiryId}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 回覆現場漲價詢問
         * @description **M1b。** LINE 的 postback 經這裡打進 `Procurement.IInquiryReplyReceiver`，
         *     **不經由 Notification 回傳事件**（ADR-012）。
         *
         *     冪等：同一個 inquiry 重複回覆，以第一次為準，第二次回 200 但不改變結果。
         *
         *     逾時未回覆的話系統會**視為照買**——所以這個端點不是阻塞路徑，晚回也不會卡住整團。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    inquiryId: components["schemas"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        accepted: boolean;
                        replyText?: string | null;
                    };
                };
            };
            responses: {
                /** @description 已記錄 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inquiryId: components["schemas"]["Id"];
                            outcome: components["schemas"]["InquiryOutcome"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description UUIDv7，32 字元十六進位，**無連字號**。
         * @example 0198c3d4e5f607189abc0123456789ab
         */
        Id: string;
        /**
         * @description ISO 4217 代碼。最小單位的位數各幣別不同——JPY 與 KRW 沒有小數位。
         * @enum {string}
         */
        Currency: "TWD" | "JPY" | "USD" | "KRW" | "EUR" | "HKD" | "CNY" | "THB" | "GBP" | "SGD";
        /**
         * @description **`amountMinor` 是最小單位**：TWD 的最小單位是分，`NT$180` = `18000`。
         *     前端只顯示不運算——加總、分攤、含運總額全部由後端回傳。
         */
        Money: {
            /**
             * Format: int64
             * @example 18000
             */
            amountMinor: number;
            currency: components["schemas"]["Currency"];
        };
        /** @description RFC 9457。**機器讀 `code`，不要讀 `title`。** */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://greygray.tw/errors/checkout.cart-empty
             */
            type: string;
            /**
             * @description 繁體中文，客服可直接照念。
             * @example 購物車是空的
             */
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
            /**
             * @description 對應 `Error.Code`。格式 `{模組}.{kebab-case}`，一經上線不可改名。
             * @example checkout.cart-empty
             */
            code: string;
            /** @description W3C traceparent。客服拿這個查整條鏈。 */
            traceId?: string | null;
            /** @description 只有欄位驗證失敗（422）才有。 */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * @description M1a 全部是 `Standard`；分級規則排 M6+。
         * @enum {string}
         */
        MemberTier: "Standard" | "Silver" | "Gold";
        /**
         * @description 雙模式唯一的分岔點：**存貨從哪來、成本何時確定**。帳務科目兩者完全相同。
         *     - `Stock` 現貨：台灣本地批發，賣之前已進貨。下單即扣可用量，狀態機短路。
         *     - `Preorder` 預購：出國現場採購，賣之後才去買。下單只登記需求，走完整 Saga。
         * @enum {string}
         */
        FulfillmentMode: "Stock" | "Preorder";
        /**
         * @description 混合訂單的出貨策略。**客人下單時就要選，不是出貨時才問。**
         *     - `ShipSeparately` 現貨先出，早點收到，付兩次運費
         *     - `HoldUntilComplete` 等回國一起出，省一次運費
         * @enum {string}
         */
        ShippingPolicy: "ShipSeparately" | "HoldUntilComplete";
        /**
         * @description **只有國內配送**——貨是親自帶回來的，沒有國際段、沒有集運。
         *     M1a 一口價：超商 60、宅配 120、自取 0（ADR-010）。
         * @enum {string}
         */
        DeliveryMethod: "ConvenienceStore" | "HomeDelivery" | "SelfPickup";
        /**
         * @description M1a 只會出現 `Flat`。其餘是 M3。
         * @enum {string}
         */
        ShippingStrategyKind: "Flat" | "WeightBracket" | "FreeOver";
        /** @enum {string} */
        CampaignStatus: "Draft" | "Open" | "Closed" | "TripInProgress" | "Returned" | "Settled" | "Cancelled";
        /**
         * @description 九個狀態，兩種模式共用同一個狀態機。
         *     `PaidAwaitingClose → ReadyToShip` 那條捷徑就是現貨。
         *
         *     刻意**沒有** `AwaitingCustomerResponse`：現場漲價時「逾時視為照買」，
         *     問客人是非阻塞的通知，不會卡住整團。這是設計選擇，不是遺漏。
         * @enum {string}
         */
        OrderStatus: "AwaitingPayment" | "PaidAwaitingClose" | "ClosedAwaitingDeparture" | "Purchasing" | "GoodsReceived" | "ReadyToShip" | "Shipped" | "Completed" | "Cancelled";
        /**
         * @description `Unavailable` = 現場缺貨，該 line 取消並退款，**其餘 line 續行，訂單不整張作廢**。
         * @enum {string}
         */
        OrderLineStatus: "Pending" | "Reserved" | "Purchased" | "Unavailable" | "Shipped" | "Completed" | "Cancelled";
        /**
         * @description M1a 只有 `ECPay`。`ExternalSettled` 是 M5 通路訂單用的位置。
         * @enum {string}
         */
        PaymentProvider: "ECPay" | "NewebPay" | "LinePay" | "ExternalSettled";
        /** @enum {string} */
        PaymentStatus: "Pending" | "Captured" | "Failed" | "Refunded" | "PartiallyRefunded";
        /** @enum {string} */
        ShipmentStatus: "Draft" | "Packed" | "Dispatched" | "InTransit" | "ArrivedAtStore" | "Delivered" | "Returned" | "Lost";
        /**
         * @description `AutoApprovedOnTimeout` = 逾時視為照買，差額由賣方吸收（團價已定死）。
         * @enum {string}
         */
        InquiryOutcome: "ConfirmedByCustomer" | "DeclinedByCustomer" | "AutoApprovedOnTimeout";
        /**
         * @description **欄位已定案（ADR-019）。** 歷史會員與訂單不從租用平台遷移，客人在新站重新註冊。
         *
         *     前端請把這份表單的欄位集中在一個 schema 檔裡，不要散在多個元件——
         *     Google 帳號串接排在 M1a 之後，屆時要在同一個流程裡插入 OAuth 的入口。
         */
        RegisterRequest: {
            /**
             * @description 台灣手機號碼。**這是登入帳號**，一經註冊不可自行修改。
             * @example 0912345678
             */
            phoneNumber: string;
            /** Format: password */
            password: string;
            displayName: string;
            /** Format: email */
            email?: string | null;
            referralCode?: string | null;
        };
        /**
         * @description **刻意不含個資明文。** 身分證字號、地址、電話、生日在 `iam` schema 內
         *     以 AES-256-GCM 應用層加密，每次存取都寫 audit。
         */
        Me: {
            id: components["schemas"]["Id"];
            displayName: string;
            tier: components["schemas"]["MemberTier"];
            isActive: boolean;
            email?: string | null;
            /**
             * @description 遮罩後的手機，例如 `0912***678`。明文不出現在 API 上。
             * @example 0912***678
             */
            phoneNumberMasked?: string | null;
            /** @description 是否已綁定 LINE。M1a 恆為 false。 */
            lineLinked?: boolean;
        };
        ShippingAddressInput: {
            recipientName: string;
            phoneNumber: string;
            postalCode: string;
            city: string;
            district: string;
            streetAddress: string;
            /** @default false */
            isDefault: boolean;
        };
        ShippingAddress: {
            id: components["schemas"]["Id"];
        } & components["schemas"]["ShippingAddressInput"];
        Category: {
            id: components["schemas"]["Id"];
            name: string;
            /** @description 圓形分類標的圖。1:1 裁切。 */
            imageUrl?: string | null;
        };
        ProductListItem: {
            id: components["schemas"]["Id"];
            name: string;
            /** @description 每個商品配 1–2 句描述（前台 UX 規則）。 */
            shortDescription?: string | null;
            /** @description 統一 1:1 裁切。 */
            imageUrl: string | null;
            /** @description 該商品所有 SKU 的最低售價。無可售 SKU 時為 null。 */
            priceFrom: components["schemas"]["Money"] | null;
            /**
             * @description 單位價格顯示字串，例如「NT$780／32 顆」。前台 UX 規則 #4。
             * @example NT$780／32 顆
             */
            unitPriceLabel?: string | null;
            /** @description 前台卡片上的標籤。已知值：`New` · `Popular` · `LastCall`。前端要容忍未知值。 */
            badges: string[];
            /** @description 登入時反映這位客戶的最愛（ADR-036）；未登入時恆為 false。 */
            isFavorited: boolean;
            mode?: components["schemas"]["FulfillmentMode"];
            /** @description `mode = Preorder` 時指向所屬的團。 */
            campaignId?: components["schemas"]["Id"] | null;
        };
        Sku: {
            id: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            weightGram: number;
            /** @description 包裹尺寸，公分。M1a 不拿來算運費（一口價），但建檔時就要填。 */
            size: {
                lengthCm: number;
                widthCm: number;
                heightCm: number;
            };
            /** @example 顆 */
            unitOfMeasure?: string | null;
            /** @example 32 */
            unitCount?: number | null;
            isActive: boolean;
            /**
             * @description 可用量 ＝ 總量 − 保留 − 通路配額（第三項 M5 前恆為 0）。
             *     `mode = Preorder` 的 SKU 這個值恆為 `0`，**但仍然可以下單**——
             *     預購是訂單驅動，下單只登記需求，不扣庫存。前端不要拿這個值擋預購。
             */
            available: number;
            /** @description 售價。現貨是標價，預購是該團的定價。 */
            price?: components["schemas"]["Money"] | null;
            campaignOfferId?: components["schemas"]["Id"] | null;
        };
        ProductDetail: {
            id: components["schemas"]["Id"];
            name: string;
            description?: string | null;
            shortDescription?: string | null;
            images: string[];
            categoryId?: components["schemas"]["Id"] | null;
            mode: components["schemas"]["FulfillmentMode"];
            /** @description `mode = Preorder` 時附上團的摘要，前端要顯示截團倒數。 */
            campaign?: components["schemas"]["CampaignListItem"] | null;
            skus: components["schemas"]["Sku"][];
            /** @description 登入時反映這位客戶的最愛（ADR-036）；未登入時恆為 false。 */
            isFavorited?: boolean;
        };
        /**
         * @description 開團 ＝ 一趟採購旅程，**1:1**。
         *     **沒有成團門檻、沒有名額上限**——下單只登記需求。
         */
        CampaignListItem: {
            id: components["schemas"]["Id"];
            title: string;
            /** @example 首爾 */
            destination: string;
            /** Format: date */
            departAt: string;
            /** Format: date */
            returnAt: string;
            /** Format: date-time */
            closesAt: string;
            status: components["schemas"]["CampaignStatus"];
            /**
             * @description **前端要用這個判斷能不能下單，不要自己拿 `closesAt` 跟現在時間比。**
             *     截團是後端的 Saga Timer 說了算，客戶端時鐘不可信。
             */
            isAcceptingOrders: boolean;
            coverImageUrl?: string | null;
        };
        CampaignDetail: components["schemas"]["CampaignListItem"] & {
            description?: string | null;
            offers: components["schemas"]["CampaignOffer"][];
        };
        CampaignOffer: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            productId: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            imageUrl?: string | null;
            /**
             * @description **開團時定死。** 現場買貴買便宜都不影響已成立的訂單——
             *     差額由賣方吸收，這是「逾時視為照買」成立的前提。
             */
            sellingPrice: components["schemas"]["Money"];
            unitPriceLabel?: string | null;
            isActive: boolean;
        };
        CartLine: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            productId: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            imageUrl?: string | null;
            mode: components["schemas"]["FulfillmentMode"];
            campaignId?: components["schemas"]["Id"] | null;
            campaignOfferId?: components["schemas"]["Id"] | null;
            quantity: number;
            unitPrice: components["schemas"]["Money"];
            /** @description 後端算好的。**前端不要自己乘。** */
            lineTotal: components["schemas"]["Money"];
            /** @description 例如「庫存只剩 2 件」或「這個團已截止收單」。有值時前端要擋結帳。 */
            availabilityWarning?: string | null;
        };
        Cart: {
            id: components["schemas"]["Id"];
            lines: components["schemas"]["CartLine"][];
            goodsTotal: components["schemas"]["Money"];
            /**
             * @description 同時含現貨與預購。為 true 時結帳必須讓客人選 `shippingPolicy`，
             *     並說明「現貨先出會付兩次運費」。
             */
            hasMixedModes: boolean;
            /** @description 客人選過配送方式之後才有值。含運總額看 `quote.grandTotal`。 */
            quote?: components["schemas"]["QuoteResult"] | null;
        };
        /**
         * @description 報價快照。M1a 費率雖然寫死一口價，這份快照仍然完整記錄——
         *     否則 M3 導入規則引擎時無法回溯比對。
         */
        QuoteResult: {
            deliveryMethod: components["schemas"]["DeliveryMethod"];
            goodsTotal: components["schemas"]["Money"];
            shippingFee: components["schemas"]["Money"];
            /** @description 購物袋顯示的**含運總額**（前台 UX 規則）。 */
            grandTotal: components["schemas"]["Money"];
            actualWeightGram?: number;
            volumetricWeightGram?: number;
            billableWeightGram?: number;
            appliedStrategy: components["schemas"]["ShippingStrategyKind"];
            /**
             * @description 人看的計價說明，例如「超商取貨一口價 NT$60」。
             *     **客服要能直接回答「為什麼收這麼多」，不用去翻程式碼。**
             */
            explain: string[];
        };
        OrderListItem: {
            id: components["schemas"]["Id"];
            /**
             * @description 給客人看與客服查的單號。**不是主鍵**，主鍵是 `id`。
             * @example GG26082800123
             */
            orderNumber: string;
            status: components["schemas"]["OrderStatus"];
            grandTotal: components["schemas"]["Money"];
            /** Format: date-time */
            placedAt: string;
            lineCount: number;
            thumbnailUrl: string | null;
        };
        OrderLine: {
            id: components["schemas"]["Id"];
            skuId: components["schemas"]["Id"];
            productId: components["schemas"]["Id"];
            name: string;
            variantName?: string | null;
            imageUrl?: string | null;
            mode: components["schemas"]["FulfillmentMode"];
            status: components["schemas"]["OrderLineStatus"];
            quantity: number;
            unitPrice: components["schemas"]["Money"];
            lineTotal: components["schemas"]["Money"];
            campaignId?: components["schemas"]["Id"] | null;
            /** @description 該 line 已退款的金額。缺貨退款後有值。 */
            refundedAmount?: components["schemas"]["Money"] | null;
        };
        Order: {
            id: components["schemas"]["Id"];
            orderNumber: string;
            status: components["schemas"]["OrderStatus"];
            shippingPolicy: components["schemas"]["ShippingPolicy"];
            deliveryMethod: components["schemas"]["DeliveryMethod"];
            goodsTotal: components["schemas"]["Money"];
            shippingFee: components["schemas"]["Money"];
            grandTotal: components["schemas"]["Money"];
            paidAmount?: components["schemas"]["Money"] | null;
            lines: components["schemas"]["OrderLine"][];
            shippingAddress?: components["schemas"]["ShippingAddress"] | null;
            /**
             * @description 取貨門市名稱（下單當時凍結，ADR-038）。**舊訂單**只存了代號，這裡會退回顯示代號——
             *     ADR-038 之前實作把代號塞進這個欄位，保持舊訂單畫面不變。
             */
            convenienceStoreName?: string | null;
            /** @description 取貨門市地址（下單當時凍結）；舊訂單與非超商取貨為 null。 */
            convenienceStoreAddress?: string | null;
            /** Format: date-time */
            placedAt: string;
            /**
             * Format: date-time
             * @description 逾期未付會自動取消（Saga Timer）。前端顯示倒數用這個，
             *     **不要自己算**——時限是後端的規則。
             */
            paymentDueAt?: string | null;
            /** @description 下單當時凍結的計價說明。運費規則之後改了也不影響這裡。 */
            quoteExplain?: string[];
        };
        /**
         * @description 綠界 7-ELEVEN 電子地圖的導轉參數（ADR-038）。前端建一個 hidden form，把 `fields` 原封不動用 `method` 送到 `action`，
         *     頂層導向。**不要改任何欄位的值**；`ExtraData` 就是選店票。
         */
        CvsMapSession: {
            selectionId: string;
            /** @enum {string} */
            method: "POST";
            /** Format: uri */
            action: string;
            fields: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        CvsStoreSelection: {
            selectionId: string;
            storeCode: string;
            storeName: string;
            storeAddress: string;
            /** @description 綠界 `CVSOutSide = 1`（離島門市）。M1a 只顯示，不擋、不加運費。 */
            isOutlying: boolean;
            /** Format: date-time */
            expiresAt: string;
        };
        /**
         * @description 綠界導轉參數。前端建一個 hidden form，把 `fields` 原封不動 POST 到 `action`。
         *     **不要自己組簽章、不要改任何欄位的值。**
         */
        PaymentInitiation: {
            provider: components["schemas"]["PaymentProvider"];
            /** @enum {string} */
            method: "POST";
            /** Format: uri */
            action: string;
            fields: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description M1b。 */
        Shipment: {
            id: components["schemas"]["Id"];
            method: components["schemas"]["DeliveryMethod"];
            status: components["schemas"]["ShipmentStatus"];
            trackingNumber?: string | null;
            /** Format: uri */
            trackingUrl?: string | null;
            /** @description 合併出貨時會有多張訂單。 */
            orderIds: components["schemas"]["Id"][];
            /** Format: date-time */
            dispatchedAt?: string | null;
            /** Format: date-time */
            deliveredAt?: string | null;
        };
    };
    responses: {
        /** @description 未登入或 session 過期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 不存在，或存在但不屬於這個使用者 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 狀態衝突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 欄位驗證失敗或業務規則不允許 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 觸發速率限制 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description 同一個使用者動作用同一把 key，重試時不變。詳見 `docs/05-API契約.md` §4。 */
        IdempotencyKey: string;
        /** @description 上一頁回傳的 `nextCursor`。第一頁不帶。 */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description gg_session=<opaque>; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000 */
        SessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
