<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GreyGray.Modules.Fulfillment.Infra</RootNamespace>
    <ModuleName>Fulfillment</ModuleName>
    <ModuleLayer>Infra</ModuleLayer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreyGray.Modules.Fulfillment.Core\GreyGray.Modules.Fulfillment.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
